config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'home#index'
  get "/checkout" => 'home#checkout'

  post "/make_payment" => "home#charge"
  get '/unsubscribe' => "home#unsubscribe"
  post '/unsubscribe' => "home#process_unsubscribe"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def index
    @products = Product.order(:price)
    promo = Promotion.find_by_id(cookies.encrypted[:promotion_id])
    @promotion = promo if promo.present? && promo.currently_active?

    if params[:tracking].present?
      tracking_info = JSON.parse(Base64.urlsafe_decode64(params[:tracking]))
      activity = ActivityTracker.find_or_initialize_by(email: tracking_info["email"], key: 'landingpage.visit')

      cookies[:email] = tracking_info["email"]

      promo = Promotion.find_by_id(tracking_info["promotion_id"])
      if promo.present?
        activity.trackable = promo
        activity.parameters = {discount: promo.label}
        cookies.encrypted[:promotion_id] = promo.id
        @promotion ||= promo if promo.currently_active?
      end

      activity.save
    end
  end

  def checkout
    # ============ Payment Related Stuff ==================
    unless params[:show_success].present?
      @product = Product.find_by_code(params[:code])

      if @product.nil?
        flash[:error] = "Please choose your package first"
        redirect_to root_path and return
      end

      # track the visits to payment page
      if cookies["email"].present?
        activity = ActivityTracker.find_or_initialize_by(email: cookies["email"], key: 'checkout.visit')
        activity.recipient = @product

        promo = Promotion.find_by_id(cookies.encrypted[:promotion_id])

        if promo.present?
          activity.trackable = promo
          activity.parameters = {discount: promo.label, sale_price: @product.promotional_price(promo)}
        end

        activity.save
      end

      @pk_key = if Rails.env.production?
        ENV["PROD_PUBLISHABLE_KEY"]
      else
        ENV["TEST_PUBLISHABLE_KEY"]
      end

      @promotion = promo if promo.present? && promo.valid_promotion?(@product)
    end
  end

  def charge
    product = Product.find_by_code(params[:product_code])
    promo   = Promotion.find_by_id(params[:promo_id])
    invoice = nil

    user = if User.find_by_email(params[:user][:email]).nil?
      temp_pw = Devise.friendly_token
      User.create!(
        email:                 params[:user][:email],
        password:              temp_pw,
        password_confirmation: temp_pw,
        temprorary_password:   true
      )
    else
      User.find_by_email(params[:user][:email])
    end

    user.first_name = params[:user][:first_name]
    user.last_name  = params[:user][:last_name]
    user.zipcode    = params[:user][:zip]
    user.save!

    # new user? add customer and then process sale
    if user.stripe_customer_id.nil?
      begin
        Payment::PaymentProcessor.save_customer!(user, params[:stripeToken])
      rescue Stripe::CardError => e
        err = e.json_body[:error][:message]
        msg = "Sorry, something went wrong while processing your payment, please try again."
        flash[:error] = err.present? ? "Sorry, #{err}, please try again." : msg

        redirect_to :back and return
      end
    end

    # make sure don't double charge
    if user.invoices.by_product(product).exists?
      flash[:error] = "You can already purchased this course. Thanks for your support!"
      redirect_to :back and return

    else
      # process sale
      begin
        invoice = product.process_sale!(user: user, promotion: promo)
        cookies.delete(:promotion_id) if cookies.encrypted[:promotion_id].present?
      rescue Payment::PaymentErrors => e
        flash[:error] = e.message
      rescue => e
        flash[:error] = "Sorry, something went wrong while processing your payment, please try again."
        redirect_to :back and return
      end
    end

    redirect_to checkout_path(show_success: true, invoice_code: invoice.try!(:code))
  end

  def unsubscribe
  end

  def process_unsubscribe
    if EmailSetting.where(email: params[:email].downcase, subscribed: false).exists?
      # do nothing, they are already on the unsubscribe list
    elsif User.where(email: params[:email]).exists? || Member.where(email: params[:email]).exists?
      EmailSetting.create(email: params[:email].downcase, subscribed: false, unsubscribed_at: Time.current)
    end

    # if we have no data on them, just return success
    flash[:success] = "You have successfully unsubscribed!"
    redirect_to :back
  end
end

app/views/home/_about_section.html.erb
<div class="container pb5em" id="about">
  <div class="row mt3em"> 
    <div class="col s12 valign">
      <%=image_tag "all-devices.png", class: " responsive-img " %>
    </div>
  </div>
  <div class="row valign-wrapper mt3em">
    <div class="col s10 offset-s1 m8 valign center">
      <h5 class="light-text">
        Modern Assets is the only program built specifically for accountants from the ground up to help make the benefits of technology and online marketing as accessible and affordable as possible.</h5>
    </div>
    <div class="col hide-on-small-only m4 valign">
      <div class="effecter demo animated z-depth-5 br-50percent">
        <%=image_tag "ma_no_frame.png", class: "responsive-img center-img"%>
      </div>
    </div>
  </div>
  <div class="row valign-wrapper mt5em hide-on-small-only">
    <div class="col s10 offset-s1 m5 valign">
      <%=image_tag "cloud_accounting.png", class: "about-illustration green-background responsive-img" %>
    </div>
    <div class="col m7 valign">
      <h5 class="light-text">
        Learn how to benefit from cloud-based technologies:
      </h5>
      <ul>
        <li><p class="light-text"><i class="material-icons small">done</i> use social media to get more business.</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> implement online scheduling to save time and increase conversions.</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> increase your website's ranking on google search results for more online traffic</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> optimize your website to get more clients</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> measure marketing success with metrics and analytics</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> and so so much more...</p></li>
      </ul>
    </div>
  </div>
  <div class="row center pt3em pb5em hide-on-small-only">
    <a class="waves-effect waves-light btn-large capitalize h6" data-scroll href="#pricing">Sign Up Today</a>
  </div>
  <div class="row mt5em hide-on-med-and-up">
    <div class="col s8 offset-s2">
      <%=image_tag "cloud_accounting.png", class:  "about-illustration green-background responsive-img" %>
    </div>
    <div class="col s12 ">
      <h5 class="mt20 light-text center">
        Learn how to benefit from cloud-based technologies:
      </h5>
      <ul>
        <li><p class="light-text"><i class="material-icons small">done</i> use social media to get more business.</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> implement online scheduling to save time and increase conversions.</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> increase your website's ranking on google search results for more online traffic</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> optimize your website to get more clients</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> measure marketing success with metrics and analytics</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> and so so much more...</p></li>
      </ul>
    </div>
  </div>
  <div class="row center pt3em pb5em hide-on-med-and-up">
    <a class="waves-effect waves-light btn-large capitalize h6" data-scroll href="#pricing">Sign Up Today</a>
  </div>
  <div class="row valign-wrapper mt5em hide-on-small-only">
    <div class="col s10 offset-s1 m5 push-m7 valign">
      <%=image_tag "integrated_offering.png", class: "about-illustration minty-background  responsive-img" %>
    </div>
    <div class="col m7 pull-m5 valign">
      <h5 class="light-text">
        Learn Anywhere, At Anytime, On Any Device 
      </h5>
      <ul>
        <li><p class="light-text"><i class="material-icons small">done</i> Dedicated &amp Secure Online Learning Platform</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> Video Tutorials</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> Downloadable Slides</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> How-To Action guides</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> Implementation Checklists</p></li>
      </ul>
    </div>
  </div>
  <div class="row center pt3em pb5em hide-on-small-only">
    <a class="waves-effect waves-light btn-large capitalize h6" data-scroll href="#pricing">Sign Up Today</a>
  </div>
  <div class="row mt5em hide-on-med-and-up">
    <div class="col s8 offset-s2">
      <%=image_tag "integrated_offering.png", class: "about-illustration minty-background responsive-img" %>
    </div>
    <div class="col s12">
      <h5 class="mt20 light-text center">
        Learn Anywhere, At Anytime, On Any Device 
      </h5>
      <ul>
        <li><p class="light-text"><i class="material-icons small">done</i> Dedicated &amp Secure Online Learning Platform</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> Video Tutorials</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> Downloadable Slides</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> How-To Action guides</p></li>
        <li><p class="light-text"><i class="material-icons small">done</i> Implementation Checklists</p></li>
      </ul>
    </div>
  </div>
  <div class="row center pt3em pb5em hide-on-med-and-up">
    <a class="waves-effect waves-light btn-large capitalize h6" data-scroll href="#pricing">Sign Up Today</a>
  </div>
</div>

app/views/home/_contact_us.html.erb
<div id="contact-us-banner" class="parallax-container">
  <div class="section  contact-us-cover valign-wrapper">
    <div class="container">
      <h2 class="header center white-text valign mb20">Still Have Questions ?</h2>
      <div class="row center">
        <h5 class="header col s8 offset-s2 white-text dark-text">Feel free to reach out if you have any other questions or just want to say hi. We'd be happy to hear from you.</h5>
      </div>
      <div class="row center">
        <a class="modal-trigger waves-effect waves-light btn-large green-third-background capitalize h6" href="#modal1">Contact Us</a>
      </div>
    </div>
  </div>
  <div class="parallax">
    <%=image_tag "contact-us.jpg", class: "z-depth-4 responsive-img" %>
  </div>
</div>

app/views/home/_curriculum_section.html.erb
<div class="minty-third-background" id="program">
    <div class="row center pt5em">
      <div class="col m8 offset-m2">
          <h3 class="">Program Outline</h3>
          <h5 class="light-text mt20">The entire Modern Assets program -- all video tutorials, downloadable slides, how-to action guides, and implementation checklists -- are broken up into manageable weekly modules. Enjoy a simple step-by-step system that helps make the process of modernizing your practice as efficient and effective as possible.</h5>
      </div>
    </div>
    <div class="row">
        <div class="col s10 offset-s1 m6 offset-m3">
            <ul class="timeline">
                <li class="timeline-item period">
                    <div class="timeline-info"></div>
                    <div class="timeline-content-top">
                        <h4 class="timeline-title">Modern Fundamentals</h4>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 1</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Brand Building</h5>
                        <p>Craft a brand that resonates with your customers, leads to higher conversions, and directly aligns with your business goals &amp personal principles.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 2</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Business Modeling</h5>
                        <p>Uncover new market opportunities, cut costs, and optimize existing services by applying tried and proven business modeling methodologies.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 3</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Customer Development</h5>
                        <p>Benefit from applying a scientific approach to meeting your ideal future customers and learn how to generate more revenue by optimizing each customer's lifetime value.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 4</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Modern Tools &amp Technologies</h5>
                        <p>Learn how to save time and provide better service by automating repetitive tasks, streamlining processes, and improving your practice's presence with the use of modern tools &amp technologies.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 5</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Process Management</h5>
                        <p>Learn work management methodologies from world thought leaders on the subject of high performance and team optimization.</p>
                    </div>
                </li>
                <li class="timeline-item period">
                    <div class="timeline-info"></div>
                    <div class="timeline-content">
                        <h4 class="timeline-title">Modern Marketing Essentials <span class="smaller">(Theory)</span></h4>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 6</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Inbound Marketing</h5>
                        <p>Attract, Convert, Close, and Delight more customers by learning how to benefit from social media, blogging, newsletter management, and much more.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 7</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Outbound Marketing</h5>
                        <p>Improve your traditional marketing efforts by applying new strategies and tools for better customer engagement and higher conversion.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 8</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Sales Funnel Engineering</h5>
                        <p>Integrate inbound and outbound marketing by learning how to engineer valuable and delightful customer journeys that are sure to convert more strangers into loyal customers. </p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 9</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Metrics &amp Analytics</h5>
                        <p>Measurement is what makes marketing a science, rather than a superstition. We will teach you how to obtain data from different marketing channels and will introduce you to the most important metrics to evaluate in any marketing campaign.</p>
                    </div>
                </li>
                <li class="timeline-item period">
                    <div class="timeline-info"></div>
                    <!-- <div class="timeline-marker"></div> -->
                    <div class="timeline-content">
                        <h4 class="timeline-title">Modern Marketing Essentials <span class="smaller">(Practice)</span></h4>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 10</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Create your Modern Marketing Strategy</h5>
                        <p>Learn how to interface business objectives with sales goals when creating a modern marketing strategy.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 11</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Development A Modern Marketing Plan</h5>
                        <p>We'll guide you along the process of interpreting your marketing strategy into a marketing plan that is ready to execute for your practice's success.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 12</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Produce Your Modern Marketing Assets</h5>
                        <p>We'll show you everything you need to know to create ready to publish, high performing digital assets for your marketing campaigns.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 13</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Launch &amp Learn</h5>
                        <p>Learn the magic behind successful product and sales launches and what actions you can take to help increase the probabilities of potential customers becoming repeat customers.</p>
                    </div>
                </li>
                <li class="timeline-item">
                    <div class="timeline-info">
                        <span>Module 14</span>
                    </div>
                    <div class="timeline-marker"></div>
                    <div class="timeline-content">
                        <h5 class="timeline-title">Continuous Improvement</h5>
                        <p>What is even more important than modernizing your practice ? Maintaining it ! Learn what metrics and data points are worth considering on a weekly, monthly, quarterly, and annual basis and how to interpret these metrics to inform adjustments you can make to improve your practice.</p>
                    </div>
                </li>

            </ul>
        </div>
    </div>
  <div class="row center pt3em pb5em">
    <a class="waves-effect waves-light btn-large capitalize h6" data-scroll href="#pricing">Sign Up Today</a>
  </div>
</div>

app/views/home/_footer.html.erb
<footer class="page-footer green-third-background">
  <div class="footer-copyright m0">
    <div class="container mo">
    <div class="row valign-wrapper m0">
      <div class="col s2 m1 valign">
        <%=image_tag "modern_assets_white.png", {class:"mt5", style:"width:100%;"}%>    
      </div>
      <div class="col s10 m11 valign">
        All Rights Reserved by 
        <a class="white-text" href="http://techtreestudio.com">Modern Assets &copy;</a> 2017 
      </div>
    </div>
    </div>
  </div>
</footer>

app/views/home/checkout.html.erb
<div class="pt3em" style="background-color: rgba(71, 180, 117, 0.5);">
  <div class="container">
    <div class="row center">
      <h2 class="white-text mb20">Modern Assets Checkout Page</h2>
      <h4 class="grey-text">You are about to make an awesome investment in your firm.</h4>
    </div>
    <div class="row pb5em">
      <% if params[:show_success] %>
        <div class="col s10 offset-s1">
          <div class="card z-depth-0 center pv2em">
            <div class="card-content">
              <div class="row">
                <h4 class="green-text">Thank you for your payment!</h4>
                <h6 class="grey-text mt20">Your confirmation code is #<%= params[:invoice_code] %>.<br /><br />You should receive an email copy of your receipt shortly.</h6>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="col s10 offset-s1 m6 ">
          <div class="card z-depth-0 center pv2em">
            <div class="card-content">
              <h4 class="green-text"><%= @product.description %></h4>
              <% if @promotion.present? && @promotion.valid_promotion?(@product) %>
                <h4 class="grey-text strikethrough light-text">Original: <%= number_to_currency(@product.price, precision: 0) %></h4>
                <h4 class="red-text">Today: <%= number_to_currency(@product.promotional_price(@promotion), precision: 0) %></h4>
              <% else %>
                <h4 class="grey-text"><%= number_to_currency(@product.price, precision: 0) %></h4>
              <% end %>

              <ul class="mb20">
                <li><h6><span class="bold-text">15 </span> Learning Modules</h6></li>
                <% if @product.code == "ACCTSTARTER" %>
                  <li><h6><span class="bold-text">6 </span> months of course acess</h6></li>
                <% else %>
                  <li><h6><span class="bold-text">Lifetime </span> access to course</h6></li>
                <% end %>
                <li><h6><span class="bold-text">All </span> video tutorials</h6></li>
                <li><h6><span class="bold-text">All </span> downloadable slides</h6></li>
                <li><h6><span class="bold-text">All </span> how-to action guides </h6></li>
                <li><h6><span class="bold-text">All </span> implementation checklists </h6></li>
                <li><h6><span class="bold-text">Access </span> to members only community </h6></li>
                <% if @product.code == "ACCTGROWTH" %>
                  <li><h6><span class="bold-text">4</span> Live Q &amp A sessions</h6></li>
                  <li><h6><span class="bold-text">Direct</span> Email support</h6></li>
                  <li><h6><span class="bold-text">Downloadable </span> Templates for all course projects</h6></li>
                <% elsif @product.code == "ACCTROCKSTAR" %>
                  <li><h6><span class="bold-text">8</span> Live Q &amp A sessions</h6></li>
                  <li><h6><span class="bold-text">Priority</span> Email support</h6></li>
                  <li><h6><span class="bold-text">Downloadable </span> Templates for all course projects</h6></li>
                  <li><h6><span class="bold-text">Launch </span> Review</h6></li>
                  <li><h6><span class="bold-text">Hand On </span> Brand Critique</h6></li>
                  <li><h6><span class="bold-text">Expert </span>review of marketing strategy</h6></li>
                  <li><h6><span class="bold-text">Hands-on </span>review of marketing plan</h6></li>
                  <li><h6><span class="bold-text">Review </span> of marketing plan</h6></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div class="col s10 offset-s1 m6 ">
          <div class="card z-depth-0 center pv2em">
            <div class="card-content">
                <div class="row payment-detail">
                  <h4 class="green-text">Payment Details</h4>
                  <h6 class="grey-text">*You will receive an email reciept after you complete the checkout using our secure payment system</h6>
                  <div class="payment-errors" style="font-weight:600;color:red;"></div>
                </div>

                <%= form_tag make_payment_path, method: :post, class: "payment-form", style: "height:100%;" do |f| %>
                  <%= hidden_field_tag :product_code, @product.code %>
                  <%= hidden_field_tag :promo_id, @promotion.try!(:id) %>

                  <div class="row">
                    <div class="input-filed col s12">
                      <%= text_field_tag '[user]first_name', nil, placeholder: "First Name", class: "validate", required: true %>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-filed col s12">
                      <%= text_field_tag '[user]last_name', nil, class: "validate", placeholder: "Last Name", required: true %>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-field col s12">
                      <%= email_field_tag '[user]email', nil, placeholder: "Email", class: "validate", required: true %>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-field col s8">
                      <%= text_field_tag '[payment]card_number', nil, placeholder: 'Card Number', class: "validate", "data-stripe" => "number", required: true %>
                    </div>

                    <div class="input-field col s4">
                      <%= text_field_tag '[payment]cvv', nil, placeholder: 'CVV', class: "validate", "data-stripe" => "cvv", required: true %>
                    </div>
                  </div>

                  <div class="row">
                    <div class="input-field col s4">
                      <%= text_field_tag '[payment]exp_month', nil, placeholder: 'MM', class: "validate", "data-stripe" => "exp-month", size: 2, required: true %>
                    </div>

                    <div class="input-field col s4">
                      <%= text_field_tag '[payment]exp_year', nil, placeholder: 'YYYY', class: "validate", "data-stripe" => "exp-year", size: 2, required: true %>
                    </div>

                    <div class="input-field col s4">
                      <%= text_field_tag '[user]zip', nil, class: "validate", placeholder: "Zip Code", size: 4, "data-strip" => "address_zip", required: true %>
                    </div>
                  </div>

                  <div class="row">
                    <%= submit_tag "Submit", class: "capitalize btn-large", style: "font-size:1.2em;", data: { disable_with: "Submitting..." } %>
                  </div>
                <% end %>
              </div>
          </div>
        </div>
      <% end %> <!-- end if show_success -->
    </div>
  </div>


  <%= content_for :javascripts do %>
  <script>
  function stripeResponseHandler(status, response) {
      if (response.error) {
        $(".payment-errors").text(response.error.message);
      }
      else {
        $(".payment-detail").append("<h4 class='green-text'>Processing...</h4>");

        var form$ = $(".payment-form");
        form$.hide();
        var token = response['id'];
        form$.append("<input type='hidden' name='stripeToken' value='" + token + "'/>");
        $("[data-stripe=number]").remove();
        $("[data-stripe=cvv]").remove();
        $("[data-stripe=exp-year]").remove();
        $("[data-stripe=exp-month]").remove();
        form$.get(0).submit();
      }
  }

  $(document).ready(function() {
    // format the credit card number
    Stripe.setPublishableKey('<%= @pk_key.to_s %>');

    $("#_paymentcard_number").formatter({ "pattern": "{{9999}} {{9999}} {{9999}} {{9999}}" });
    $("#_paymentcvv").formatter({ "pattern": "{{9999}}" });
    $("#_userzip").formatter({ "pattern": "{{99999}}" });
    $("#_paymentexp_month").formatter({ "pattern": "{{99}}" });
    $("#_paymentexp_year").formatter({ "pattern": "{{9999}}" });

    $(".payment-form").submit(function(event) {

      var $form = $(this);
      $('.submit').attr("disabled", "disabled");
      Stripe.card.createToken($form, stripeResponseHandler);

      // prevent the form from submitting with the default action
      return false;
    });
  });
  </script>
  <% end %>

app/views/home/unsubscribe.html.erb
<div class="pt3em" style="background-color: rgba(71, 180, 117, 0.5);">
  <div class="container">
    <div class="row pb5em">
      <div class="col s10 offset-s1">
        <div class="card z-depth-0 center pv2em">
          <div class="card-content">
            <div class="row">
              <h4 class="green-text">Sorry to see your go...</h4>
              <h6 class="grey-text mt20">Enter your email below to unsubscribe from all communications from Modern Assets</h6>
            </div>

            <%= form_tag unsubscribe_path, method: :post, class: "payment-form", style: "height:100%;" do |f| %>
              <div class="row">
                <div class="input-field col s8 offset-s2">
                  <%= email_field_tag 'email', nil, placeholder: "Your Email", class: "validate", required: true %>
                </div>
              </div>

              <div class="row">
                <%= submit_tag "Unsubscribe", class: "capitalize btn-large", style: "font-size:1.2em;", data: { disable_with: "Submitting..." } %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>